version: '3.7'

x-db-env: &db-env
  MYSQL_DATABASE: 'gallery_project'
  MYSQL_USER: 'gp_user'
  MYSQL_PASSWORD: 'gp_password'

services:
  mysql:
    container_name: image-database
    restart: always
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - "./files/database:/var/lib/mysql"
    environment:
      <<: *db-env
      MYSQL_ROOT_PASSWORD: 'root_password'

  python:
    restart: always
    build: ./server
    container_name: python-server
    ports:
      - 8000:8000
    volumes:
      - "./files/images:/server/images"
    environment:
      <<: *db-env
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: 3306